routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\CustomAuthController;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::group([
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function()
{
    Route::get('/', [HomeController::class, 'home'])->name('home');
    Route::get('newss', [NewsController::class, 'frontIndex'])->name('news.frontIndex');
    Route::get('newss/{news}', [NewsController::class, 'frontShow'])->name('news.frontShow');
}
);

Route::get('login', [CustomAuthController::class, 'login'])->name('auth.login');
Route::post('login-user/', [CustomAuthController::class, 'loginUser'])->name('auth.login.user');
Route::get('logout/', [CustomAuthController::class, 'logout'])->name('auth.logout');

Route::group(['prefix' => 'panel', 'middleware' => 'auth'], function()
{
    Route::resource('news', NewsController::class);
});

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Translatable\HasTranslations;

class News extends Model
{
    use HasFactory, HasTranslations;

    public $translatable = ['title', 'description'];

    protected $fillable = ['title', 'description', 'image'];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/CustomAuthController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;

class CustomAuthController extends Controller
{
    public function login()
    {
        return view('auth.login');
    }

    public function loginUser(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'password'=>'required|min:5|max:12',
        ]);

        $credentials = $request->except(['_token']);

        if (auth()->attempt($credentials)) {

            return redirect()->route('news.index')
                ->with('success', 'You are logged in successfully !');

        }else{
            session()->flash('message', 'Invalid credentials');
            return redirect()->back();
        }
    }

    public function logout()
    {
        auth()->logout();

        return redirect()->route('auth.login');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\News;

class HomeController extends Controller
{
    public function home()
    {
        $newss = News::latest()->get();

        return view('home', compact('newss'));
    }
}

app/Http/Controllers/LoginController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class LoginController extends Controller
{
    public function loginForm()
    {
        return view('auth.login');
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\NewsRequest;
use Illuminate\Support\Str;
use App\Models\News;

class NewsController extends Controller
{
    public function frontIndex()
    {
        $newss = News::latest()->get();

        return view('news', compact('newss'));
    }

    public function frontShow(News $news)
    {
        $all_news = News::latest()->get();

        return view('news_show', compact('news', 'all_news'));
    }

    public function index()
    {
        $newss = News::latest()->get();

        return view('admin.news', compact('newss'));
    }

    public function create()
    {
        return view('admin.create');
    }

    public function store(NewsRequest $request)
    {
        $attributes = $request->validated();

        if($request->hasFile('image')){
            $image = $request->file('image');
            $destinationPath = public_path('admin_assets/images');
            $profileImage = Str::random(30) . '.' . $image->getClientOriginalExtension();
            $image->move($destinationPath, $profileImage);
            $attributes['image'] = $profileImage;
        }

        News::create($attributes);

        return redirect()->route('news.index')
            ->with('success','Product created successfully.');
    }

    public function edit(News $news)
    {
        return view('admin.edit', compact('news'));
    }

    public function update(News $news, NewsRequest $request)
    {
        $attributes = $request->validated();

        if ($request->hasFile('image')) {
            $image = $request->file('image');
            if(file_exists(public_path('admin_assets/images/' . $news->image))){
                unlink(public_path('admin_assets/images/' . $news->image));
            }
            $destinationPath = public_path('admin_assets/images');
            $profileImage = Str::random(30) . '.' . $image->getClientOriginalExtension();
            $image->move($destinationPath, $profileImage);
            $attributes['image'] = $profileImage;
        }else{
            unset($attributes['image']);
        }

        $news->update($attributes);

        return redirect()->route('news.index')
            ->with('success','Product updated successfully');

    }

    public function destroy(News $news)
    {
        if (file_exists(public_path('admin_assets/images/' . $news->image))) {
            unlink(public_path('admin_assets/images/' . $news->image));
        }

        $news->delete();

        return redirect()->route('news.index')
            ->with('success','Product deleted successfully');
    }
}

resources/views/admin/create.blade.php
@extends('admin.layout')

@section('css')
<link rel="stylesheet" href="{{ asset('admin_assets/ckeditor/contents.css') }}">
@endsection

@section('content')
    <div class="page-content">

        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card-body">
                    <h6 class="card-title m-4">Habar goş</h6>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <strong>Ýalňyşlyk!</strong> Maglumatlarňyz doly derejede doldurylmadyk! Haýyş edýäris boş öýlere maglumatlary giriziň.
                        </div>
                    @endif
                    <form action="{{route('news.store')}}" enctype="multipart/form-data" method="POST" class="forms-sample">
                        @csrf
                        <div class="d-flex justify-content-between">
                            <div class="form-group flex-grow-1 m-4">
                                <label for="exampleInputUsername1" id="alo">Ady TK</label>
                                <input type="text" name="title[tk]" value="{{old('title[tk]')}}" class="form-control" id="exampleInputUsername1" autocomplete="off" placeholder="Ady">
                            </div>
                            <div class="form-group flex-grow-1 m-4">
                                <label for="exampleInputUsername1" id="alo">Ady RU</label>
                                <input type="text" name="title[ru]" value="{{old('title[ru]')}}" class="form-control" id="exampleInputUsername1" autocomplete="off" placeholder="Ady">
                            </div>
                            <div class="form-group flex-grow-1 m-4">
                                <label for="exampleInputUsername1" id="alo">Ady EN</label>
                                <input type="text" name="title[en]" value="{{old('title[en]')}}" class="form-control" id="exampleInputUsername1" autocomplete="off" placeholder="Ady">
                            </div>
                        </div>

                        <div class="d-flex justify-content-between">
                            <div class="form-group flex-grow-1 m-4">
                                <label for="exampleFormControlTextarea1">Giňişleýin TK</label>
                                <textarea class="form-control" name="description[tk]" placeholder="Giňişleýin" id="ckeditor" rows="10">{{old('description[tk]')}}</textarea>
                            </div>
                            <div class="form-group flex-grow-1 m-4">
                                <label for="exampleFormControlTextarea1">Giňişleýin RU</label>
                                <textarea class="form-control" name="description[ru]" placeholder="Giňişleýin" id="ckeditor2" rows="10">{{old('description[ru]')}}</textarea>
                            </div>
                            <div class="form-group flex-grow-1 m-4">
                                <label for="exampleFormControlTextarea1">Giňişleýin EN</label>
                                <textarea class="form-control" name="description[en]" placeholder="Giňişleýin" id="ckeditor3" rows="10">{{old('description[en]')}}</textarea>
                            </div>
                        </div>

                        <div class="form-group col-6">
                            <label>Suraty</label>
                            <input type="file" name="image" id="file-upload-default" class="file-upload-default">
                            <div id="file-upload-browse" class="input-group col-xs-12">
                                <input type="text" name="image" class="form-control file-upload-info" disabled="" placeholder="Upload Image">
                                <span class="input-group-append">
                                    <button class="file-upload-browse btn btn-primary" type="button">Ýükle</button>
                                </span>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary mr-2">Döret</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
<script src="{{ asset('admin_assets/ckeditor/ckeditor.js') }}" type="text/javascript" ></script>
<script type="text/javascript">
    $(function() {
        CKEDITOR.replace('ckeditor');
        CKEDITOR.replace('ckeditor2');
        CKEDITOR.replace('ckeditor3');
    })
</script>
@endsection

resources/views/admin/edit.blade.php
@extends('admin.layout')

@section('css')
<link rel="stylesheet" href="{{ asset('admin_assets/ckeditor/contents.css') }}">
@endsection

@section('content')
    <div class="page-content">

        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card-body">
                    <h6 class="card-title m-4">Habar üýtget</h6><br>
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <strong>Whoops!</strong> There were some problems with your input.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{route('news.update', $news)}}" enctype="multipart/form-data" method="POST" class="forms-sample">
                        @csrf
                        @method('PUT')
                        <div class="d-flex justify-content-between">
                            <div class="form-group flex-grow-1 m-4">
                                <label for="exampleInputUsername1" id="alo">Ady TK</label>
                                <input type="text" name="title[tk]" value="{{$news->getTranslation('title', 'tk')}}" class="form-control" id="exampleInputUsername1" autocomplete="off" placeholder="Ady">
                            </div>
                            <div class="form-group flex-grow-1 m-4">
                                <label for="exampleInputUsername1" id="alo">Ady RU</label>
                                <input type="text" name="title[ru]" value="{{$news->getTranslation('title', 'ru')}}" class="form-control" id="exampleInputUsername1" autocomplete="off" placeholder="Ady">
                            </div>
                            <div class="form-group flex-grow-1 m-4">
                                <label for="exampleInputUsername1" id="alo">Ady EN</label>
                                <input type="text" name="title[en]" value="{{$news->getTranslation('title', 'en')}}" class="form-control" id="exampleInputUsername1" autocomplete="off" placeholder="Ady">
                            </div>
                        </div>

                        <div class="d-flex justify-content-between">
                            <div class="form-group flex-grow-1 m-4">
                                <label for="exampleFormControlTextarea1">Giňişleýin TK</label>
                                <textarea class="form-control" name="description[tk]" placeholder="Giňişleýin" id="ckeditor" rows="10">{{$news->getTranslation('description', 'tk')}}</textarea>
                            </div>
                            <div class="form-group flex-grow-1 m-4">
                                <label for="exampleFormControlTextarea1">Giňişleýin RU</label>
                                <textarea class="form-control" name="description[ru]" placeholder="Giňişleýin" id="ckeditor2" rows="10">{{$news->getTranslation('description', 'ru')}}</textarea>
                            </div>
                            <div class="form-group flex-grow-1 m-4">
                                <label for="exampleFormControlTextarea1">Giňişleýin EN</label>
                                <textarea class="form-control" name="description[en]" placeholder="Giňişleýin" id="ckeditor3" rows="10">{{$news->getTranslation('description', 'en')}}</textarea>
                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Suraty:</strong>
                                <input type="file" name="image" class="form-control" placeholder="image">
                                <img class="edit-img" src="{{ asset('admin_assets/images/' . $news->image) }}" width="300px">
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary mr-2">Üýtget</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
<script src="{{ asset('admin_assets/ckeditor/ckeditor.js') }}" type="text/javascript" ></script>
<script type="text/javascript">
    $(function() {
        CKEDITOR.replace('ckeditor');
        CKEDITOR.replace('ckeditor2');
        CKEDITOR.replace('ckeditor3');
    })
</script>
@endsection

resources/views/admin/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Panel</title>
    <!-- core:css -->
    <link rel="stylesheet" href="{{asset('admin_assets/vendors/core/core.css')}}">
    <link rel="stylesheet" href="{{asset('admin_assets/fonts/feather-font/css/iconfont.css')}}">
    <link rel="stylesheet" href="{{asset('admin_assets/vendors/flag-icon-css/css/flag-icon.min.css')}}">
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{{asset('admin_assets/css/demo_1/style.css')}}">
    @yield('css')
    <style>
        a {
            text-decoration: none;
            color: inherit;
        }

        svg {
            cursor: pointer !important;
            transition: 0.3s;
        }

        svg:hover {
            color: #727cf5
        }

        table td img {
            border-radius: unset!important;
            width: 80px!important;
            height: 80px!important;
        }

        .edit-img {
            margin-top: 20px;
        }
        .navbar {
            top: 0;
        }
    </style>
</head>
<body>
<div class="main-wrapper">
    <nav class="sidebar">
        <div class="sidebar-header">
            <a href="#" class="sidebar-brand">
                Admin
            </a>
            <div class="sidebar-toggler not-active">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div class="sidebar-body">
            <ul class="nav">
                <li class="nav-item nav-category">Administrasiýa</li>
                <li class="nav-item">
                    <a href="{{route('news.index')}}" class="nav-link">
                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-bag"><path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"></path><line x1="3" y1="6" x2="21" y2="6"></line><path d="M16 10a4 4 0 0 1-8 0"></path></svg>
                        <span class="link-title mt-1">Habarlar</span>
                    </a>
                </li>
            </ul>
        </div>
    </nav>


    <div class="page-wrapper">

        <!-- partial:../../includes/_navbar.html -->
        <nav class="navbar">
            <a href="#" class="sidebar-toggler">
                <i data-feather="menu"></i>
            </a>
            <div class="navbar-content">
                <ul class="navbar-nav">


                    <li class="nav-item dropdown nav-profile">
                        <a class="nav-link dropdown-toggle" href="#" id="profileDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Logout
                        </a>
                        <div class="dropdown-menu" aria-labelledby="profileDropdown">
                            <div class="dropdown-header d-flex flex-column align-items-center">
                                <div class="figure mb-3">
{{--                                    <img src="https://via.placeholder.com/80x80" alt="">--}}
                                </div>
                                <div class="info text-center">
                                    <p class="name font-weight-bold mb-0">Amiah Burton</p>
                                    <p class="email text-muted mb-3">amiahburton@gmail.com</p>
                                </div>
                            </div>
                            <div class="dropdown-body">
                                <ul class="profile-nav p-0 pt-3">
                                    <li class="nav-item">
                                        <a href="{{ route('auth.logout') }}" class="nav-link">
                                            <i data-feather="log-out"></i>
                                            <span>Log Out</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
        <!-- partial -->

        @yield('content')

        <!-- partial:../../includes/_footer.html -->
        <footer class="footer d-flex flex-column flex-md-row align-items-center justify-content-between">

        </footer>
        <!-- partial -->

    </div>
</div>
<script src="{{asset('admin_assets/vendors/core/core.js')}}"></script>
<script src="{{asset('admin_assets/vendors/feather-icons/feather.min.js')}}"></script>
<script src="{{asset('admin_assets/js/template.js')}}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{{asset('admin_assets/vendors/tinymce/tinymce.min.js')}}"></script>
<script src="{{asset('admin_assets/js/tinymce.js')}}"></script>
@yield('js')

<script>
    $(document).ready(function(){
        $('#file-upload-browse').click(function(){ $('#file-upload-default').trigger('click')});
        $('#m-file-upload-browse').click(function(){ $('#m-file-upload-default').trigger('click')});
    })
</script>
</body>
</html>

resources/views/admin/news.blade.php
@extends('admin.layout')

@section('content')
<div class="page-content">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between mb-4 pr-4">
                    <h4 class="card-title">Habarlar</h4>
                    <a href="{{route('news.create')}}"><button class="btn btn-primary">Goş</button></a>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>Ady</th>
                                <th>
                                    Maglumat
                                </th>
                                <th>
                                    Senesi
                                </th>
                                <th>
                                    Suraty
                                </th>
                                <th>
                                    Üýtget
                                </th>
                                <th>
                                    Poz
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach($newss as $news)
                                    <tr>
                                        <td class="py-1">
                                            {!! \Illuminate\Support\Str::limit($news->getTranslation('title', 'tk'), 20, $end='...') !!}
                                        </td>
                                        <td>
                                            {!! \Illuminate\Support\Str::limit($news->getTranslation('description', 'tk'), 50, $end='...') !!}
                                        </td>
                                        <td>
                                            {{date_format($news->created_at,'d.m.Y')}}
                                        </td>
                                        <td>
                                            <img src="{{ asset('admin_assets/images/' . $news->image) }}" alt="image">
                                        </td>
                                        <td>
                                           <a href="{{route('news.edit', $news)}}"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg></a>
                                        </td>
                                        <td>
                                            <svg data-toggle="modal" data-target="#exampleModal" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>

                                            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header" style="color: #856404; background-color: #fff3cd; border-bottom: 1px solid #ffe79e !important">
                                                        <h5 class="modal-title" id="exampleModalLabel">Duýduryş !</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                        </div>
                                                        <div class="modal-body">
                                                        Siz pozmak isleýärsiňizmi ?!
                                                        </div>
                                                        <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Ýok</button>
                                                        <form action="{{ route('news.destroy', $news) }}" method="post">
                                                            @csrf
                                                            @method('DELETE')
                                                            <input class="btn btn-primary" type="submit" value="Hawa">
                                                        </form>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/app/footer.blade.php
<div class="container-fluid footer py-3">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-xl-4 col-lg-5 col-md-6 col-sm-8 d-flex align-items-center" id="footer-logo">
          <img class="footer-logo-image me-3" src="{{ asset('images/image-by-item-and-alias 1.png') }}">
          <div class="footer-logo-text">{!! __('base.logo') !!}</div>
        </div>
    </div>
    <div class="row justify-content-center mt-4">
      <div class="col-xl-4 col-lg-5 col-md-7 col-sm-9 text-center align-items-center" id="footer-menu">
          <a class="footer-menu-item text-decoration-none" href="#">{{ __('base.home') }}</a>
        <a class="footer-menu-item text-decoration-none" href="#">{{ __('base.us') }}</a>
        <a class="footer-menu-item text-decoration-none" href="{{ route('news.frontIndex') }}">{{ __('base.news') }}</a>
        <a class="footer-menu-item me-0 text-decoration-none" href="#">{{ __('base.gallery') }}</a>
      </div>
    </div>
    <div class="row justify-content-center mt-4">
      <div class="col-xxl-7 col-lg-9 align-items-center" id="footer-about">
        <div class="footer-about-item" href="#">{{ __('base.phone') }}</div>
        <div class="footer-about-item" href="#">{{ __('base.fax') }}</div>
        <div class="footer-about-item" href="#">{{ __('base.email') }}</div>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col text-center"><div class="footer-copyright mb-0">{{ __('base.copyright') }}</div></div>
    </div>
    </div>
  </div>
  <script src="{{ asset('js/bootstrap.bundle.js') }}"></script>
</body>
</html>

resources/views/home.blade.php
@extends('app\layout')
@section('content')
<div class="gal-tit mt-4">{{ __('base.news') }}</div>
<div class="row mt-4 news-card">
    @foreach ($newss as $news)
    <div class="col-lg-3 col-md-6 p-0">
        <div class="news-card shadow mb-25">
        <a class="text-decoration-none d-block" href="{{ route('news.frontShow', $news) }}">
          <div class="news-card-image">
            <img src="{{ asset('admin_assets/images/' . $news->image) }}">
          </div>
          <div class="news-caption">
            <div class="news-title">{{ \Illuminate\Support\Str::limit($news->title, 100, $end='...') }}</div>
            <div class="news-text">{!! \Illuminate\Support\Str::limit($news->description, 100, $end='...') !!}</div>
            <div class="news-date">{{ date_format($news->created_at,'d.m.Y') }}</div>
          </div>
        </a>
      </div>
      </div>
    @endforeach
</div>
@endsection

resources/views/news.blade.php
@include('app\header')
<div class="container news-all">
    <div class="gal-tit mt-4">{{ __('base.news') }}</div>
    <div class="row mt-4 news-card">
        @foreach ($newss as $news)
        <div class="col-lg-3 col-md-6 p-0">
            <div class="news-card shadow mb-25">
            <a class="text-decoration-none d-block" href="{{ route('news.frontShow', $news) }}">
            <div class="news-card-image">
                <img src="{{ asset('admin_assets/images/' . $news->image) }}">
            </div>
            <div class="news-caption">
                <div class="news-title">{{  \Illuminate\Support\Str::limit($news->title, 100, $end='...')  }}</div>
                <div class="news-text">{!! \Illuminate\Support\Str::limit($news->description, 200, $end='...') !!}</div>
                <div class="news-date">{{ date_format($news->created_at,'d.m.Y') }}</div>
            </div>
            </a>
        </div>
        </div>
        @endforeach
    </div>
</div>
@include('app.footer')